// <auto-generated />
using FantasyNameGen.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FantasyNameGen.Migrations.Surnames
{
    [DbContext(typeof(SurnamesContext))]
    [Migration("20180801094805_Surname")]
    partial class Surname
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FantasyNameGen.Models.Surname", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Common");

                    b.Property<string>("CyrilSurname");

                    b.Property<string>("RomanSurname");

                    b.HasKey("Id");

                    b.ToTable("Surnames");
                });
#pragma warning restore 612, 618
        }
    }
}
